---
title: "Costeo y Evaluación de Reservas Marinas"
subtitle: "Una guía para gestores ambientales"
author: "Juan Carlos Villaseñor-Derbez"
date: |
  Bren School of Environmental Science & Management, UCSB
  juancarlos@ucsb.edu
documentclass: krantz
site: bookdown::bookdown_site
bibliography: [references.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: "jcvdav/curso_marea"
description: "Manual de evaluación de reservas marinas para gestores ambientales."
cover-image: "img/flow.tif"
favicon: "marea.ico"
csl: "FMS.csl"
---

```{r, echo = F, message = F, warning = F}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
```


# Antes de empezar {-}

Este manual es la segunda iteración de los esfuerzos por impulsar el uso de metodologías estandarizadas para la evaluación de reservas marinas. Trabajos anteriores incluyen el manual generalizado de evaluación de reservas marinas en México [@villaseorderbez_2017] y la publicación arbitrada que presenta a [MAREA](https://turfeffect.shinyapps.io/marea/) como una herramienta amigable y gratuita [@villasenorderbez_2018]. Esta versión del manual pretende incorporar partes de ambos trabajos, pero también incluye una serie de ejercicios prácticos para el uso de MAREA y la nueva App de Costeo de Reservas. Además, el manual está públicamente disponible en [internet](https://jcvdav.github.io/curso_marea/), donde el lector puede descargar el manual como PDF o EPUB para Kindle[^*].

[^*]: El manual puede ser compartido y distribuido libremente. Sin embargo, esta versión se encuentra en proceso de edición y puede contener errores. Comentarios y sugerencias de edición son bienvenidos en [juancarlos@ucsb.edu](juancarlos@ucsb.edu) o con el botón de edición en la barra de herramientas de la versión online. La versión más actualizada siempre estará disponible en internet en:  [https://jcvdav.github.io/curso_marea](https://jcvdav.github.io/curso_marea). El manual fue generado utilizando `bookdown` [@R-bookdown].

Aunque el manual y la Aplicación para Evaluación de Reservas Marinas (MAREA) pueden ser utilizados alrededor del mundo, es importante mencionar que el proyecto fue diseñado para evaluar la efectividad de las reservas marinas en México. Por lo tanto, las metodologías utilizadas reflejan las necesidades de las comunidades costeras mexicanas, y no debe de interpretarse como un conjunto de instrucciones definitivas. Aún así, creemos que la guía ha sido creada para permitir su aplicación en otros lugares con el mismo fin.

## Requisitos

MAREA y la nueva App de Costeo de Reservas son aplicaciones web desarrolladas en R utilizando el paquete `shiny` [@R-base;@R-shiny]. Para poder utilizarlas es necesario tener un explorador de internet y una conexión estable. Aunque no siempre tenemos acceso a internet, utilizar aplicaciones *"en la nuve"* nos evita problemas de compatibilidad entre diferentes sistemas operativos. Si tienes un explorador de internet y una conexión estable, puedes usar estas Apps.

Este manual va acompañado de datos sintéticos para los ejercicios prácticos. Puedes descargar estos materiales gratuitamente en el [repositorio de GitHub](https://github.com/jcvdav/curso_marea_datos), y distribuirlos con atribución.

## Sobre este libro

### Motivación

El desarrollo de MAREA fue motivado por la necesidad de proveer metodologías estandarizadas para evaluar las zonas de refugio pesquero, un tipo de reservas marinas diseñadas como herramientas de manejo pesquero [@nom]. MAREA es una plataforma amigable que usa técnicas econométricas de inferencia de causalidad para estimar el efecto de una reserva en una serie de indicadores de interés. Los resultados generados pueden ser comunicados con las tarjetas de puntuaciones o con el reporte automatizado que el usuario puede descargar.

La aplicación de costeo es mucho más sencilla. Esta app permite obtener los costos de operación asociados al diseño, implementación y monitoreo y evaluación de una reserva marina comunitaria siguiendo la metodología de [COBI](https://cobi.org.mx/) [@uribe_2010]. Aunque el usuario puede agregar diferentes rubros, las categorías predeterminadas están basadas en la experiencia que COBI ha adquirido a lo largo de los años.

### Estructura

Este manual se divide en tres partes. La Parte 1 presenta la App de Costeo (Capítulo \@ref(app-de-costeo)) y describe las secciones de la ventana, así como su uso y funcionalidad.

La Parte 2 se compone de tres capítulos: El Capítulo \@ref(antecedentes) presenta una revisión de otros métodos usados para evaluar reservas marinas. El Capítulo \@ref(evaluacion-de-reservas) introduce la metodología usada por MAREA, con un énfasis en los *Objetivos* e *Indicadores* utilizados, así como el modelo de Diferencias entre Diferencias para estimar el efecto de la reserva. Finalmente el Capítulo \@ref(uso-de-marea) provee una introducción a MAREA, incluyendo el tipo y formato de datos necesarios, los 6 pasos de la evaluación, la interpretación de los resultados y una discusión de sus capacidades y limitaciones.

La Parte 3 consta de dos capítulos. El Capítulo \@ref(ejercicios-con-marea) contiene cinco ejercicios, representativos de operaciones comunes a realiza con MAREA. El Capítulo \@ref(errores-y-soluciones) presenta algunos de los errores comunes y sus soluciones.





